spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

image:
  local-path: src/main/resources/file/
  server-url: http://localhost:8080/images/
  profileImage-name: profile-
  dummyImage-name: not-found

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG